### PR TITLE
Add conditional to prevent skipping GUIDs

### LINKED ISSUE #8: Add option to modify GUIDs
As #6 disables modifying the GUID column by default, and there are still some scenarios where it is desirable to modify GUIDs, such as on the first deployment to a production environment.

A flag could be added to modify GUIDs when performing a search-replace on URLs.

### PR DESCRIPTION
**Pull request by robrecord**
If skip_guid is passed as false, GUIDs will not be skipped

Usage:
sync.sh <environment> <site> db <push|pull> --extra-vars "skip_guids=false"

Fixes #8 and #7 
Replaces #6

### CODE REVIEW

**Comment by pacotole** [comment]
Thank you!
It is a good contribution but I think that `skip_guids_column` should be `false` by default. The usual workflow is in production to use the production domain.

It could be usefull for some cases (like migrations) where you need to keep the GUIDs but the usual is to replace the development GUIDs by the production ones. And when syncs `prod => dev => prod` the final GUIDs have not changed.

**Comment by robrecord** [comment]
OK fair point; I think the decision was the opposite in the wp-cli repository which is why I went this way.

I will switch it when i have a minute.

Thanks

**Comment by robrecord** [comment]
I think the rationale was that it doesn't matter what the GUID is, only that it doesn't change once it's been out "in the wild", on production. So I still think it shouldn't be altered by default because it's a disruptive change.

Even if a post was created on dev, then pushed to prod, the GUID being a dev URL wouldn't be a problem. But if the GUID from production was a non-prod URL, then pulled down and pushed back up and modified in the process, that could be a problem to feed readers.

Unless you think that is too unlikely to be an issue. What do you think?

**Comment by pacotole** [comment]
I think it's very unlikely.

I also don't think it's appropriate to publicly reveal development/staging urls.

For example, we create almost all the content initially on the staging server and then we synchronize `stag => dev => prod` and we are not interested in revealing our staging urls.

As I said at the beginning I see it very useful for a migration or change of domain.

**Comment by robrecord** [comment]
Thanks @pacotole 

Apologies for the delay; I have changed this behaviour as suggested.

**Pull request merged**
